// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdzhvbchtxdmbnrazmjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtkemh2YmNodHhkbWJucmF6bWpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMDcwMzcsImV4cCI6MjA2Njg4MzAzN30.3gbB0fLK1FfO61w7WYzKltoN5WVioqgsb9FzaeqD2I4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});